/**
 * Atom type definitions with Zod schemas.
 *
 * Atoms are the fundamental unit of BinderOS — every piece of information
 * (task, fact, event, decision, insight) is an atom. Zod schemas are the
 * single source of truth; TypeScript types are inferred from them.
 *
 * Links are typed, directional edges (CONTEXT.md decision).
 * Type-aware link rules enforced in Phase 2 compute layer.
 */

import { z } from 'zod/v4';

// --- Enums ---

export const AtomStatus = z.enum([
  'open',
  'in-progress',
  'waiting',
  'done',
  'cancelled',
  'archived',
]);
export type AtomStatus = z.infer<typeof AtomStatus>;

export const AtomType = z.enum([
  'task',
  'fact',
  'event',
  'decision',
  'insight',
]);
export type AtomType = z.infer<typeof AtomType>;

// --- Link schema ---

export const AtomLinkSchema = z.object({
  targetId: z.string().uuid(),
  relationshipType: z.string(), // e.g., "belongs-to", "depends-on", "relates-to"
  direction: z.enum(['forward', 'backward']),
});
export type AtomLink = z.infer<typeof AtomLinkSchema>;

// --- Base atom shape (shared fields) ---

const BaseAtomFields = {
  id: z.string().uuid(),
  content: z.string(), // Markdown string
  title: z.string(),
  status: AtomStatus,
  links: z.array(AtomLinkSchema),
  sectionId: z.string().uuid().optional(),
  sectionItemId: z.string().uuid().optional(),
  created_at: z.number(), // Unix ms timestamp
  updated_at: z.number(), // Unix ms timestamp
};

// --- Type-specific atom schemas (discriminated union members) ---

export const TaskAtomSchema = z.object({
  ...BaseAtomFields,
  type: z.literal('task'),
  dueDate: z.number().optional(),
  scheduledDate: z.number().optional(),
});
export type TaskAtom = z.infer<typeof TaskAtomSchema>;

export const FactAtomSchema = z.object({
  ...BaseAtomFields,
  type: z.literal('fact'),
});
export type FactAtom = z.infer<typeof FactAtomSchema>;

export const EventAtomSchema = z.object({
  ...BaseAtomFields,
  type: z.literal('event'),
  eventDate: z.number().optional(),
});
export type EventAtom = z.infer<typeof EventAtomSchema>;

export const DecisionAtomSchema = z.object({
  ...BaseAtomFields,
  type: z.literal('decision'),
});
export type DecisionAtom = z.infer<typeof DecisionAtomSchema>;

export const InsightAtomSchema = z.object({
  ...BaseAtomFields,
  type: z.literal('insight'),
});
export type InsightAtom = z.infer<typeof InsightAtomSchema>;

// --- Discriminated union of all atom types ---

export const AtomSchema = z.discriminatedUnion('type', [
  TaskAtomSchema,
  FactAtomSchema,
  EventAtomSchema,
  DecisionAtomSchema,
  InsightAtomSchema,
]);
export type Atom = z.infer<typeof AtomSchema>;

// --- Inbox item (pre-classification, type is optional) ---

export const InboxItemSchema = z.object({
  ...BaseAtomFields,
  type: AtomType.optional(),
  isInbox: z.literal(true),
});
export type InboxItem = z.infer<typeof InboxItemSchema>;

// --- Create atom input (id and timestamps generated by worker) ---

export const CreateAtomInputSchema = z.discriminatedUnion('type', [
  TaskAtomSchema.omit({ id: true, created_at: true, updated_at: true }),
  FactAtomSchema.omit({ id: true, created_at: true, updated_at: true }),
  EventAtomSchema.omit({ id: true, created_at: true, updated_at: true }),
  DecisionAtomSchema.omit({ id: true, created_at: true, updated_at: true }),
  InsightAtomSchema.omit({ id: true, created_at: true, updated_at: true }),
]);
export type CreateAtomInput = z.infer<typeof CreateAtomInputSchema>;
