/**
 * cognitive-signals.ts -- Auto-generated signal protocol types.
 *
 * Generated by: scripts/train/62_signal_compositor.py --codegen
 * Protocol version: 1
 *
 * DO NOT EDIT MANUALLY -- regenerate with:
 *   python -u scripts/train/62_signal_compositor.py --codegen
 */

// ---------------------------------------------------------------------------
// Signal protocol version
// ---------------------------------------------------------------------------
export const SIGNAL_PROTOCOL_VERSION = 1;

// ---------------------------------------------------------------------------
// Cognitive dimension types (one per model)
// ---------------------------------------------------------------------------
export type COGNITIVELOADLabel = 'trivial' | 'routine' | 'complex' | 'deep';
export type COLLABORATIONTYPELabel = 'solo' | 'delegation' | 'collaboration';
export type EMOTIONALVALENCELabel = 'positive' | 'neutral' | 'negative' | 'anxious';
export type ENERGYLEVELLabel = 'high-focus' | 'medium-focus' | 'low-energy';
export type GTDHORIZONLabel = 'runway' | '10k-projects' | '20k-areas' | '30k-goals' | '40k-vision';
export type INFORMATIONLIFECYCLELabel = 'ephemeral' | 'short-lived' | 'stable' | 'permanent';
export type KNOWLEDGEDOMAINLabel = 'work' | 'personal' | 'health' | 'finance' | 'creative' | 'tech' | 'social' | 'admin';
export type PRIORITYMATRIXLabel = 'urgent-important' | 'urgent-not-important' | 'not-urgent-important' | 'not-urgent-not-important';
export type REVIEWCADENCELabel = 'daily' | 'weekly' | 'monthly' | 'quarterly';
export type TIMEESTIMATELabel = 'quick' | 'short' | 'medium' | 'long';

// ---------------------------------------------------------------------------
// Model IDs
// ---------------------------------------------------------------------------
export const COGNITIVE_MODEL_IDS = [
  'cognitive-load',
  'collaboration-type',
  'emotional-valence',
  'energy-level',
  'gtd-horizon',
  'information-lifecycle',
  'knowledge-domain',
  'priority-matrix',
  'review-cadence',
  'time-estimate',
] as const;

export type CognitiveModelId = (typeof COGNITIVE_MODEL_IDS)[number];

// ---------------------------------------------------------------------------
// Dimension names
// ---------------------------------------------------------------------------
export const COGNITIVE_DIMENSIONS = {
  'cognitive-load': 'complexity',
  'collaboration-type': 'collaboration',
  'emotional-valence': 'emotion',
  'energy-level': 'energy',
  'gtd-horizon': 'horizon',
  'information-lifecycle': 'lifecycle',
  'knowledge-domain': 'domain',
  'priority-matrix': 'priority',
  'review-cadence': 'review',
  'time-estimate': 'duration',
} as const;

export type CognitiveDimension = (typeof COGNITIVE_DIMENSIONS)[CognitiveModelId];

// ---------------------------------------------------------------------------
// Confidence thresholds
// ---------------------------------------------------------------------------
export const COGNITIVE_THRESHOLDS: Record<CognitiveModelId, number> = {
  'cognitive-load': 0.55,
  'collaboration-type': 0.65,
  'emotional-valence': 0.55,
  'energy-level': 0.6,
  'gtd-horizon': 0.55,
  'information-lifecycle': 0.55,
  'knowledge-domain': 0.6,
  'priority-matrix': 0.65,
  'review-cadence': 0.5,
  'time-estimate': 0.55,
};

// ---------------------------------------------------------------------------
// Single cognitive signal (output from one model)
// ---------------------------------------------------------------------------
export interface CognitiveSignal {
  /** Which model produced this signal */
  modelId: CognitiveModelId;
  /** The semantic dimension (e.g., 'priority', 'energy') */
  dimension: CognitiveDimension;
  /** Signal type: categorical (unordered), ordinal (ordered), binary */
  signalType: 'categorical' | 'ordinal' | 'binary';
  /** Per-label probability scores */
  scores: Record<string, number>;
  /** Highest-scoring label */
  topLabel: string;
  /** Confidence (max probability) */
  confidence: number;
  /** Whether confidence exceeds model's threshold */
  accepted: boolean;
}

// ---------------------------------------------------------------------------
// Composite signal (output from compositor rules)
// ---------------------------------------------------------------------------
export type CompositeSignalName =
  | 'context-switch-cost'
  | 'deep-work-block'
  | 'delegate-now'
  | 'low-energy-batch'
  | 'meeting-prep-domain'
  | 'promote-to-project'
  | 'quick-win'
  | 'review-cadence-mismatch'
  | 'stale-risk'
  | 'stress-risk'
  ;

export interface CompositeSignal {
  /** Rule that produced this signal */
  ruleName: string;
  /** The composite signal name */
  signal: CompositeSignalName;
  /** The computed value */
  value: boolean | string | number;
  /** Which model signals contributed */
  inputs: CognitiveModelId[];
}

// ---------------------------------------------------------------------------
// Full signal vector for an item (all models + composites)
// ---------------------------------------------------------------------------
export interface SignalVector {
  /** Signals from individual cognitive models */
  signals: Partial<Record<CognitiveModelId, CognitiveSignal>>;
  /** Derived composite signals from compositor rules */
  composites: CompositeSignal[];
  /** Total inference time in ms */
  totalMs: number;
  /** Protocol version */
  protocolVersion: number;
}

// ---------------------------------------------------------------------------
// Compositor rule definition
// ---------------------------------------------------------------------------
export interface CompositorRule {
  name: string;
  inputs: CognitiveModelId[];
  outputSignal: CompositeSignalName;
  evaluate: (signals: SignalVector['signals']) => CompositeSignal | null;
}

// ---------------------------------------------------------------------------
// Built-in compositor rules
// ---------------------------------------------------------------------------
export const COMPOSITOR_RULES: CompositorRule[] = [
  {
    name: 'quick-win-detector',
    inputs: ['priority-matrix', 'time-estimate'],
    outputSignal: 'quick-win',
    evaluate: (signals) => {
      const priority_matrix = signals['priority-matrix'];
      if (!priority_matrix?.accepted) return null;
      const time_estimate = signals['time-estimate'];
      if (!time_estimate?.accepted) return null;
      // Condition: priority-matrix == 'urgent-important' AND time-estimate == 'quick'
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'quick-win-detector',
        signal: 'quick-win',
        value: true,
        inputs: ['priority-matrix', 'time-estimate'],
      };
    },
  },
  {
    name: 'delegation-candidate',
    inputs: ['collaboration-type', 'priority-matrix'],
    outputSignal: 'delegate-now',
    evaluate: (signals) => {
      const collaboration_type = signals['collaboration-type'];
      if (!collaboration_type?.accepted) return null;
      const priority_matrix = signals['priority-matrix'];
      if (!priority_matrix?.accepted) return null;
      // Condition: collaboration-type == 'delegation' AND priority-matrix == 'urgent-not-important'
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'delegation-candidate',
        signal: 'delegate-now',
        value: true,
        inputs: ['collaboration-type', 'priority-matrix'],
      };
    },
  },
  {
    name: 'deep-work-batch',
    inputs: ['energy-level', 'cognitive-load', 'time-estimate'],
    outputSignal: 'deep-work-block',
    evaluate: (signals) => {
      const energy_level = signals['energy-level'];
      if (!energy_level?.accepted) return null;
      const cognitive_load = signals['cognitive-load'];
      if (!cognitive_load?.accepted) return null;
      const time_estimate = signals['time-estimate'];
      if (!time_estimate?.accepted) return null;
      // Condition: energy-level == 'high-focus' AND cognitive-load == 'deep' AND time-estimate in ('medium', 'long')
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'deep-work-batch',
        signal: 'deep-work-block',
        value: true,
        inputs: ['energy-level', 'cognitive-load', 'time-estimate'],
      };
    },
  },
  {
    name: 'stress-flag',
    inputs: ['emotional-valence', 'priority-matrix', 'time-estimate'],
    outputSignal: 'stress-risk',
    evaluate: (signals) => {
      const emotional_valence = signals['emotional-valence'];
      if (!emotional_valence?.accepted) return null;
      const priority_matrix = signals['priority-matrix'];
      if (!priority_matrix?.accepted) return null;
      const time_estimate = signals['time-estimate'];
      if (!time_estimate?.accepted) return null;
      // Condition: emotional-valence == 'anxious' AND priority-matrix in ('urgent-important', 'urgent-not-important')
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'stress-flag',
        signal: 'stress-risk',
        value: true,
        inputs: ['emotional-valence', 'priority-matrix', 'time-estimate'],
      };
    },
  },
  {
    name: 'stale-item-alert',
    inputs: ['information-lifecycle', 'review-cadence'],
    outputSignal: 'stale-risk',
    evaluate: (signals) => {
      const information_lifecycle = signals['information-lifecycle'];
      if (!information_lifecycle?.accepted) return null;
      const review_cadence = signals['review-cadence'];
      if (!review_cadence?.accepted) return null;
      // Condition: information-lifecycle == 'ephemeral' AND review-cadence != 'daily'
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'stale-item-alert',
        signal: 'stale-risk',
        value: true,
        inputs: ['information-lifecycle', 'review-cadence'],
      };
    },
  },
  {
    name: 'strategic-review',
    inputs: ['gtd-horizon', 'review-cadence'],
    outputSignal: 'review-cadence-mismatch',
    evaluate: (signals) => {
      const gtd_horizon = signals['gtd-horizon'];
      if (!gtd_horizon?.accepted) return null;
      const review_cadence = signals['review-cadence'];
      if (!review_cadence?.accepted) return null;
      // Condition: gtd-horizon in ('30k-goals', '40k-vision') AND review-cadence in ('daily', 'weekly')
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'strategic-review',
        signal: 'review-cadence-mismatch',
        value: "suggest-monthly",
        inputs: ['gtd-horizon', 'review-cadence'],
      };
    },
  },
  {
    name: 'low-energy-batch',
    inputs: ['energy-level', 'cognitive-load'],
    outputSignal: 'low-energy-batch',
    evaluate: (signals) => {
      const energy_level = signals['energy-level'];
      if (!energy_level?.accepted) return null;
      const cognitive_load = signals['cognitive-load'];
      if (!cognitive_load?.accepted) return null;
      // Condition: energy-level == 'low-energy' AND cognitive-load == 'trivial'
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'low-energy-batch',
        signal: 'low-energy-batch',
        value: true,
        inputs: ['energy-level', 'cognitive-load'],
      };
    },
  },
  {
    name: 'context-switch-cost',
    inputs: ['knowledge-domain', 'cognitive-load'],
    outputSignal: 'context-switch-cost',
    evaluate: (signals) => {
      const knowledge_domain = signals['knowledge-domain'];
      if (!knowledge_domain?.accepted) return null;
      const cognitive_load = signals['cognitive-load'];
      if (!cognitive_load?.accepted) return null;
      // Condition: cognitive-load in ('complex', 'deep')
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'context-switch-cost',
        signal: 'context-switch-cost',
        value: "high",
        inputs: ['knowledge-domain', 'cognitive-load'],
      };
    },
  },
  {
    name: 'project-promotion',
    inputs: ['gtd-horizon', 'time-estimate', 'cognitive-load'],
    outputSignal: 'promote-to-project',
    evaluate: (signals) => {
      const gtd_horizon = signals['gtd-horizon'];
      if (!gtd_horizon?.accepted) return null;
      const time_estimate = signals['time-estimate'];
      if (!time_estimate?.accepted) return null;
      const cognitive_load = signals['cognitive-load'];
      if (!cognitive_load?.accepted) return null;
      // Condition: gtd-horizon == 'runway' AND time-estimate == 'long' AND cognitive-load in ('complex', 'deep')
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'project-promotion',
        signal: 'promote-to-project',
        value: true,
        inputs: ['gtd-horizon', 'time-estimate', 'cognitive-load'],
      };
    },
  },
  {
    name: 'meeting-prep',
    inputs: ['collaboration-type', 'knowledge-domain'],
    outputSignal: 'meeting-prep-domain',
    evaluate: (signals) => {
      const collaboration_type = signals['collaboration-type'];
      if (!collaboration_type?.accepted) return null;
      const knowledge_domain = signals['knowledge-domain'];
      if (!knowledge_domain?.accepted) return null;
      // Condition: collaboration-type == 'collaboration'
      // TODO: Implement full condition logic for production
      return {
        ruleName: 'meeting-prep',
        signal: 'meeting-prep-domain',
        value: "{knowledge-domain.top_label}",
        inputs: ['collaboration-type', 'knowledge-domain'],
      };
    },
  },
];

// ---------------------------------------------------------------------------
// Hydrate compositor rules from JSON config
// ---------------------------------------------------------------------------

/**
 * Import the CompositorRuleConfig type only.
 * Type-only imports do not create runtime circular deps.
 * cognitive-signals.ts NEVER imports from binder-types at runtime.
 */
import type { CompositorRuleConfig } from '../../config/binder-types/schema';

/**
 * Convert JSON-serializable CompositorRuleConfig objects into runtime
 * CompositorRule objects with evaluate() functions.
 *
 * The hydration function interprets the declarative condition DSL:
 *   - For each clause, checks signals[modelId]?.accepted && topLabel comparison.
 *   - AND = all clauses must evaluate true.
 *   - OR = any clause must evaluate true.
 *
 * CRITICAL: This function accepts CompositorRuleConfig[] as a parameter.
 * It does NOT call getBinderConfig() — the caller provides the configs.
 * This keeps cognitive-signals.ts free from any binder-types import.
 *
 * @example
 *   const rules = hydrateCompositorRules(getBinderConfig().compositorRules);
 *   const composites = evaluateComposites(signals, rules);
 */
export function hydrateCompositorRules(configs: CompositorRuleConfig[]): CompositorRule[] {
  return configs.map((cfg) => ({
    name: cfg.name,
    inputs: cfg.inputs,
    outputSignal: cfg.outputSignal as CompositeSignalName,
    evaluate: (signals: SignalVector['signals']): CompositeSignal | null => {
      const { operator, clauses } = cfg.condition;

      const clauseResults = clauses.map((clause) => {
        const signal = signals[clause.modelId];
        if (!signal?.accepted) return false;
        const topLabel = signal.topLabel;
        if (clause.op === '==') {
          return topLabel === clause.label;
        } else if (clause.op === 'in') {
          return Array.isArray(clause.label) && clause.label.includes(topLabel);
        } else if (clause.op === '!=') {
          return topLabel !== clause.label;
        }
        return false;
      });

      const conditionMet =
        operator === 'AND'
          ? clauseResults.every(Boolean)
          : clauseResults.some(Boolean);

      if (!conditionMet) return null;

      // Determine output value: use outputValue if specified, else true
      let value: boolean | string | number = true;
      if (cfg.outputValue !== undefined) {
        // Handle template interpolation: {knowledge-domain.top_label}
        const tmpl = cfg.outputValue;
        if (tmpl.startsWith('{') && tmpl.endsWith('}')) {
          const expr = tmpl.slice(1, -1); // e.g. "knowledge-domain.top_label"
          const [modelId, field] = expr.split('.');
          if (modelId && field === 'top_label' && modelId in signals) {
            const s = signals[modelId as CognitiveModelId];
            value = s?.topLabel ?? tmpl;
          } else {
            value = tmpl;
          }
        } else {
          value = tmpl;
        }
      }

      return {
        ruleName: cfg.name,
        signal: cfg.outputSignal as CompositeSignalName,
        value,
        inputs: cfg.inputs,
      };
    },
  }));
}

// ---------------------------------------------------------------------------
// Evaluate all compositor rules against a signal vector
// ---------------------------------------------------------------------------

/**
 * Evaluate compositor rules against a signal vector.
 *
 * @param signals - The signal vector to evaluate.
 * @param rules - Optional rule set. When provided (e.g. hydrated from binder config),
 *   those rules are used. When omitted, falls back to the built-in COMPOSITOR_RULES.
 *
 * The `rules` parameter enables binder-type-specific compositor logic while
 * preserving backward compatibility for callers that don't pass rules.
 */
export function evaluateComposites(
  signals: SignalVector['signals'],
  /** @deprecated Use hydrateCompositorRules(getBinderConfig().compositorRules) and pass here */
  rules?: CompositorRule[],
): CompositeSignal[] {
  const activeRules = rules ?? COMPOSITOR_RULES;
  const results: CompositeSignal[] = [];
  for (const rule of activeRules) {
    const result = rule.evaluate(signals);
    if (result) results.push(result);
  }
  return results;
}

// ---------------------------------------------------------------------------
// Create an empty signal vector
// ---------------------------------------------------------------------------
export function createEmptySignalVector(): SignalVector {
  return {
    signals: {},
    composites: [],
    totalMs: 0,
    protocolVersion: SIGNAL_PROTOCOL_VERSION,
  };
}
