"""
61_train_sequence_model.py -- Train LSTM sequence-context model and export to ONNX.

Loads the sequence training data generated by 60_generate_sequence_data.py,
trains a lightweight LSTM model on next-embedding prediction (cosine similarity
loss), exports to public/models/sequence-context.onnx using dynamo=True with
opset 18, and validates immediately with onnxruntime.

Output:
    public/models/sequence-context.onnx   (< 500KB)
    scripts/train/sequence/sequence_model_frozen.pt   (for classifier retraining)

Usage:
    python -u scripts/train/sequence/61_train_sequence_model.py
"""

import sys
import time
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).parent.resolve()
REPO_ROOT = SCRIPT_DIR.parent.parent.parent
DATA_PATH = SCRIPT_DIR / "sequence_training_data.npz"
MODEL_OUTPUT = REPO_ROOT / "public" / "models" / "sequence-context.onnx"
FROZEN_MODEL_PATH = SCRIPT_DIR / "sequence_model_frozen.pt"

MAX_WINDOW = 7
INPUT_DIM = 384
HIDDEN_DIM = 64
OUTPUT_DIM = 128
NUM_LAYERS = 1


# ---------------------------------------------------------------------------
# Model definition
# ---------------------------------------------------------------------------
def build_model():
    import torch
    import torch.nn as nn

    class SequenceContextModel(nn.Module):
        """
        Lightweight LSTM that compresses a variable-length embedding sequence
        into a 128-dim context vector.

        Input:  (seq_len, 1, 384)   -- sequence of MiniLM embeddings
        Output: (1, 128)            -- context vector
        """

        def __init__(
            self,
            input_size: int = INPUT_DIM,
            hidden_size: int = HIDDEN_DIM,
            output_size: int = OUTPUT_DIM,
            num_layers: int = NUM_LAYERS,
        ):
            super().__init__()
            self.lstm = nn.LSTM(
                input_size=input_size,
                hidden_size=hidden_size,
                num_layers=num_layers,
                batch_first=False,
            )
            self.proj = nn.Linear(hidden_size, output_size)

        def forward(self, x):
            # x: (seq_len, 1, input_size)
            _, (h_n, _) = self.lstm(x)
            # h_n: (num_layers, 1, hidden_size)
            h = h_n[-1]        # (1, hidden_size)
            out = self.proj(h)  # (1, output_size)
            return out

    return SequenceContextModel()


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------
def train(model, X_train: np.ndarray, y_train: np.ndarray, n_epochs: int = 80):
    import torch
    import torch.nn as nn
    import torch.nn.functional as F

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=n_epochs)

    X_tensor = torch.from_numpy(X_train)  # (N, MAX_WINDOW, 384)
    y_tensor = torch.from_numpy(y_train)  # (N, 384)

    # Project targets to 128-dim via a fixed random matrix (same as output dim)
    # We train end-to-end: context vector should be directionally similar to
    # the first 128 dims of the target (they share the same semantic space).
    # Simpler: use cosine loss between context and a linear projection of target.
    target_proj = nn.Linear(INPUT_DIM, OUTPUT_DIM, bias=False)
    nn.init.orthogonal_(target_proj.weight)
    for p in target_proj.parameters():
        p.requires_grad = False

    y_projected = target_proj(y_tensor).detach()  # (N, 128)

    n_samples = X_tensor.shape[0]
    batch_size = min(256, n_samples)
    n_batches = (n_samples + batch_size - 1) // batch_size

    model.train()
    print(f"\n=== Training LSTM ===")
    print(f"Samples: {n_samples}, Epochs: {n_epochs}, Batch: {batch_size}")

    for epoch in range(n_epochs):
        perm = torch.randperm(n_samples)
        epoch_loss = 0.0

        for b in range(n_batches):
            idx = perm[b * batch_size : (b + 1) * batch_size]
            x_batch = X_tensor[idx]          # (B, MAX_WINDOW, 384)
            y_batch = y_projected[idx]        # (B, 128)

            # Convert to seq-first, add batch dim of 1 (process one at a time)
            # For efficiency, process full batch: reshape to (MAX_WINDOW, B, 384)
            x_seq = x_batch.permute(1, 0, 2)  # (MAX_WINDOW, B, 384)

            optimizer.zero_grad()

            # Forward: we need to support variable batch sizes
            # Use batch_first=False LSTM with proper input shape
            _, (h_n, _) = model.lstm(x_seq)
            h = h_n[-1]         # (B, hidden_size)
            out = model.proj(h)  # (B, output_size)

            # Cosine similarity loss (maximize cosine → minimize 1 - cosine)
            loss = (1.0 - F.cosine_similarity(out, y_batch, dim=1)).mean()

            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            epoch_loss += loss.item()

        scheduler.step()

        if (epoch + 1) % 10 == 0 or epoch == 0:
            avg_loss = epoch_loss / n_batches
            print(f"  Epoch {epoch+1:3d}/{n_epochs}: loss={avg_loss:.4f}")

    print("Training complete.")
    return model


# ---------------------------------------------------------------------------
# ONNX export
# ---------------------------------------------------------------------------
def export_onnx(model, output_path: Path) -> None:
    import torch

    model.eval()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Dummy input: (seq_len=5, 1, 384)
    dummy = torch.zeros(5, 1, INPUT_DIM)

    print(f"\n=== ONNX Export ===")
    print(f"Output: {output_path}")

    # Use dynamo=True per STATE.md decision (only stable path for LSTM + dynamic axes)
    try:
        export_output = torch.onnx.export(
            model,
            (dummy,),
            str(output_path),
            dynamo=True,
            fallback=True,
            opset_version=18,
            input_names=["embeddings"],
            output_names=["context"],
            dynamic_axes={"embeddings": {0: "seq_len"}},
        )
        print("dynamo export succeeded.")
    except Exception as e:
        print(f"dynamo export failed ({e}), falling back to legacy export...")
        torch.onnx.export(
            model,
            dummy,
            str(output_path),
            opset_version=18,
            input_names=["embeddings"],
            output_names=["context"],
            dynamic_axes={"embeddings": {0: "seq_len"}},
        )
        print("Legacy ONNX export succeeded.")

    size_bytes = output_path.stat().st_size
    size_kb = size_bytes / 1024
    print(f"File size: {size_kb:.1f} KB ({size_bytes} bytes)")

    if size_bytes > 512_000:
        print(f"WARNING: Model is {size_kb:.1f} KB, exceeds 500KB target!")
    else:
        print(f"PASS: Model is under 500KB ({size_kb:.1f} KB)")


def validate_onnx(model_path: Path) -> None:
    """Quick in-Python validation before the Node.js pass."""
    import onnx
    import onnxruntime as ort

    print(f"\n=== Python ONNX Validation ===")

    # Graph check
    onnx_model = onnx.load(str(model_path))
    onnx.checker.check_model(onnx_model)
    print("ONNX graph check: PASS")

    sess = ort.InferenceSession(str(model_path))
    input_name = sess.get_inputs()[0].name
    print(f"Input name: {input_name}")
    print(f"Output name: {sess.get_outputs()[0].name}")

    for seq_len in [1, 3, 5, 7]:
        x = np.random.randn(seq_len, 1, INPUT_DIM).astype(np.float32)
        out = sess.run(None, {input_name: x})[0]
        assert out.shape[-1] == OUTPUT_DIM, f"Expected last dim {OUTPUT_DIM}, got {out.shape}"
        assert not np.allclose(out, 0), f"Output is all zeros for seq_len={seq_len}"
        print(f"  seq_len={seq_len}: output shape={out.shape} — PASS")

    print("Python ONNX validation: PASS")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    start_time = time.time()
    print("=" * 60)
    print("61_train_sequence_model.py")
    print("=" * 60)

    # Check data
    if not DATA_PATH.exists():
        print(f"ERROR: Training data not found at {DATA_PATH}")
        print("Run: python -u scripts/train/sequence/60_generate_sequence_data.py")
        sys.exit(1)

    # Load data
    print(f"\nLoading data from {DATA_PATH}...")
    data = np.load(str(DATA_PATH))
    X_train = data["X_train"]   # (N, MAX_WINDOW, 384)
    y_train = data["y_train"]   # (N, 384)
    window_sizes = data["window_sizes"]

    print(f"X_train: {X_train.shape}")
    print(f"y_train: {y_train.shape}")
    for N in [3, 5, 7]:
        count = (window_sizes == N).sum()
        print(f"  N={N}: {count} samples")

    import torch

    # Build and train model
    model = build_model()
    n_params = sum(p.numel() for p in model.parameters())
    print(f"\nModel parameters: {n_params:,}")
    print(f"Architecture: LSTM({INPUT_DIM} -> {HIDDEN_DIM}) + Linear({HIDDEN_DIM} -> {OUTPUT_DIM})")

    model = train(model, X_train, y_train, n_epochs=80)

    # Save frozen model for classifier retraining
    model.eval()
    torch.save(model.state_dict(), str(FROZEN_MODEL_PATH))
    print(f"\nFrozen model saved: {FROZEN_MODEL_PATH}")

    # Export ONNX
    export_onnx(model, MODEL_OUTPUT)

    # Validate
    validate_onnx(MODEL_OUTPUT)

    elapsed = time.time() - start_time
    print(f"\nTotal time: {elapsed:.1f}s")
    print(f"\nOutput: {MODEL_OUTPUT}")
    print("Done.")


if __name__ == "__main__":
    main()
